<a href="https://colab.research.google.com/github/Dysaca22/Python-EZ-ACM-/blob/main/Python_EZ(ACM)_Redes_Neuronales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Redes Neuronales

Libreria Sklearn - redes neuronales \\
https://scikit-learn.org/stable/modules/neural_networks_supervised.html


Libreria Sklearn - datasets (Iris) \\
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html

Libreria Sklearn - train_test_split \\
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html?highlight=train_test_split#sklearn.model_selection.train_test_split

Libreria Sklearn - matriz de confusión \\
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html

Libreria Sklearn - score de precisión \\
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

Libreria tensorflow - redes neuronales \\
https://www.tensorflow.org/

Libreria tensorflow.keras.models - agrupa capas \\
https://www.tensorflow.org/api_docs/python/tf/keras/Model

Libreria tensorflow.keras.layers - API \\
https://www.tensorflow.org/api_docs/python/tf/keras/Input

Libreria tensorflow.keras.callbacks - retroceso \\
https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/Callback

## Prueba #1 - datos generados

### Definir el conjunto y modelo a usar para predicción de datos

In [ ]:
# Importamos la libreria (redes neurionales por clasificación)
from sklearn.neural_network import MLPClassifier
# Creamos el conjunto de datos de entrada (tener en cuenta que es de dimensión 2 cada elemeneto)
X = [[0., 0.], [1., 1.]]
# Creamos el conjunto de datos de salida (no tienen que ser de la misma dimesión que los de entrada)
y = [0, 1]
# Definimos el modelo MLPClassifier (predecir a que clase pertenecen un conjunto de datos usando redes neuronales)
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
  # Dos capas ocultas una de 5 neuronas y otra de 2 neuronas

### Entrenamos los datos

In [ ]:
clf.fit(X, y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

### Predecimos algunos valores con los datos entrenados

In [ ]:
clf.predict([[2., 2.], [-2., -1.]])
# Vemos como calsifico el primer elemento en 1 y el segundo en 0

array([1, 0])

## Prueba #2 - datasets

### Cargamos una base de datos de sklearn

In [ ]:
# Importamos la libreria (bases de datos)
from sklearn import datasets
# Cargamos los datos iris
iris = datasets.load_iris()
# Datos de entrada (tomamos todas las filas y dos columnas)
X = iris.data[:, :2]
# Datos de salida
y = iris.target

### Separamos los datos en entrenamiento y prueba

In [ ]:
# Importamos libreria (datos entrenamiento y prueba)
from sklearn.model_selection import train_test_split
# Dividimos nuestros datos en 4 conjuntos dos de entrenamiento y dos de prueba (entrada, salida)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
  # Los datos de prueba son 33% de los datos totales

### Definimos el modelo

In [ ]:
# Definimos el modelo MLPClassifier (predecir a que clase pertenecen un conjunto de datos usando redes neuronales)
ejemplo = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
  # Dos capas ocultas una de 5 neuronas y otra de 2 neuronas

### Entrenamos los datos

In [ ]:
ejemplo.fit(X_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

### Predecimos datos, dando como entrada los datos de prueba

In [ ]:
y_resultado = ejemplo.predict(X_test)

### Mostramos los datos predichos

In [ ]:
y_resultado

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 1, 1, 2, 0,
       0, 1, 2, 2, 2, 2])

### Mostramos los datos ah obtener (datos de prueba salida), para compararlos con los obtenidos

In [ ]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

## Verificación de datos predichos

In [ ]:
# Importamos la libreria (evaluar la precisión de una clasificación)
from sklearn.metrics import confusion_matrix

### Aplicamos la matriz
Mientras los datos esten mas concentrados en la diagonal principal, mas preciso es el sistema

In [ ]:
confusion_matrix(y_test, y_resultado)

array([[19,  0,  0],
       [ 0, 10,  5],
       [ 0,  2, 14]])

In [ ]:
# Importamos la libreria (hallar que tan bueno en porcentaje es nuestra predicción)
from sklearn.metrics import accuracy_score

### Calculamos nuestro score de predicción

In [ ]:
accuracy_score(y_test, y_resultado)

0.86

## Prueba #3 - Tensorflow
Otro metodo para hacer predicciones

In [ ]:
# Importamos las librerias
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dropout, Dense
from tensorflow.keras.callbacks import EarlyStopping
import numpy as np

# Definimos el punto máximo y parada
cbez = EarlyStopping(monitor='accuracy',
                      min_delta=0.01,
                      mode='max',
                      patience=100,
                      )

# Agregamos las capas a la red
model1 = Sequential()
model1.add(Input(shape=(2,)))
model1.add(Dense(5, activation='sigmoid'))#'sigmoid'))
model1.add(Dropout(0.25))
model1.add(Dense(2, activation='sigmoid'))
model1.add(Dense(3, activation='sigmoid'))
model1.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
#%%

# Entrenamos los datos
epk1 = 500
model1.fit(X_train,
           y_train,
           epochs=epk1,
           callbacks=[cbez],
           validation_split=0.2           
           )
#%%

Epoch 1/500
3/3 [==============================] - 1s 98ms/step - loss: 1.1550 - accuracy: 0.3375 - val_loss: 1.2302 - val_accuracy: 0.2000
Epoch 2/500
3/3 [==============================] - 0s 15ms/step - loss: 1.1672 - accuracy: 0.3375 - val_loss: 1.2274 - val_accuracy: 0.2000
Epoch 3/500
3/3 [==============================] - 0s 15ms/step - loss: 1.1527 - accuracy: 0.3375 - val_loss: 1.2243 - val_accuracy: 0.2000
Epoch 4/500
3/3 [==============================] - 0s 15ms/step - loss: 1.1491 - accuracy: 0.3375 - val_loss: 1.2219 - val_accuracy: 0.2000
Epoch 5/500
3/3 [==============================] - 0s 21ms/step - loss: 1.1523 - accuracy: 0.3375 - val_loss: 1.2196 - val_accuracy: 0.2000
Epoch 6/500
3/3 [==============================] - 0s 17ms/step - loss: 1.1428 - accuracy: 0.3375 - val_loss: 1.2171 - val_accuracy: 0.2000
Epoch 7/500
3/3 [==============================] - 0s 17ms/step - loss: 1.1396 - accuracy: 0.3375 - val_loss: 1.2148 - val_accuracy: 0.2000
Epoch 8/500
3/3 [===

### Predecimos los valores

In [ ]:
y_new = np.argmax(model1.predict(X_test), axis=1)
y_esperado = y_test
y_predicho = y_new

### Obtenemos la matriz de presición

In [ ]:
confusion_matrix(y_esperado,y_predicho)


array([[19,  0,  0],
       [ 1, 14,  0],
       [ 0, 16,  0]])

### Vemos el score

In [ ]:
accuracy_score(y_esperado, y_predicho)

0.66